### ISSUE TITLE
Эффект мутной картинки у svg при hover

### ISSUE THREAD

**Issue by anton-marchenko** [Kristina1996/angular-electron#56]
https://github.com/Kristina1996/surv-shell/blob/9f7c8e5404c841fa4cfb6711d06d060bfcd4df99/src/app/shared/components/icon-button/icon-button.component.scss#L7

Заменить transform: scale на явное изменение высоты и ширины иконки. Тогда не будет эффекта мутной картинки при анимации.

**Comment by stanislawru** [comment]
Who can close the issue, @anton-marchenko, you?
