### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by anton-marchenko** [Kristina1996/angular-electron#6]
Список замечаний по коду

- https://github.com/Kristina1996/angular-electron/commit/b7fdfd389c071e02bff193325c8ddd859988b0cd#r35070507
- https://github.com/Kristina1996/angular-electron/commit/770a04d1c6a9ba33cfb6e1b4c276082e8f1648df#r35053771
- https://github.com/Kristina1996/angular-electron/commit/e0e10c1d3fdc70afa5d43e9fba145282471e4197#r35070565

**Comment by anton-marchenko** [comment]
https://github.com/Kristina1996/surv-shell/blob/master/src/app/shared/components/files-menu/files-menu.component.html#L8
onChooseFile

**Comment by anton-marchenko** [comment]
https://github.com/Kristina1996/surv-shell/blob/master/src/app/shared/components/files-menu/files-menu.component.scss#L8
https://github.com/Kristina1996/surv-shell/blob/master/src/app/shared/components/files-menu/files-menu.component.scss#L4

Богатство вариантов единиц изменения для размеров и отступов привести к единому (px) - во **всём** коде

**Comment by anton-marchenko** [comment]
https://github.com/Kristina1996/surv-shell/blob/master/src/app/shared/components/new-report-modal/new-report-modal.component.ts#L58

Можно сделать getFirstItem - по аналогии с Last

**Comment by stanislawru** [comment]
Попробую взять задачу на себя.

**Comment by stanislawru** [comment]
Экспресс-проверка показала, что b7fdfd3#r35070507 и 770a04d#r35053771 уже сделаны, но тут не отмечены, как сделанные. Что ты ещё сделала, @Kristina1996?

**Comment by stanislawru** [comment]
Продолженная проверка и работа также показали, что
- e0e10c1#r35070565 Кристина тоже учла;
- у https://github.com/Kristina1996/surv-shell/issues/6#issuecomment-531763397 суть замечания непонятна (@anton-marchenko?);
- https://github.com/Kristina1996/surv-shell/issues/6#issuecomment-531763991 я исправил в части 0em;
- https://github.com/Kristina1996/surv-shell/issues/6#issuecomment-531768040, похоже, Кристиной сделано.

То есть, вроде как, всё. Pull request создал, после его слияния и комментария Антона на моё его упоминание выше задачу можно будет закрыть.

**Comment by anton-marchenko** [comment]
`у #6 (comment) суть замечания непонятна (@anton-marchenko?);`
@stanislawru - Тоже уже исправлено.
