### ISSUE TITLE
Валидация на латиницу

### ISSUE THREAD

**Issue by Kristina1996** [Kristina1996/angular-electron#66]

**Comment by stanislawru** [comment]
В чём суть данной задачи?

**Comment by Kristina1996** [comment]
@stanislawru 
Как описал мне Артём Солдатов эту проблему: в поле "Имя сотрудника" можно писать только латинскими буквами, так как СУРВ не понимает наши имена русскими буквами, поэтому надо производить валидацию.

**Comment by stanislawru** [comment]
@Kristina1996, закрой, пожалуйста, эту задачу.

@norranlol, твоё пожелание мы реализовали. ;-)
